# Arquivo de Configuração da Netlify

[build]
  # Esta linha diz para a Netlify que a pasta raiz do seu site é a pasta atual.
  publish = "."
  # Esta linha diz à Netlify onde encontrar as Funções Serverless.
  functions = "netlify/functions/"